
# setup database h2

spring:
  datasource:
    url: jdbc:h2:file:./data/flyway-migration
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

# setup h2 local database concole

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: admin
    password: password
    baseline-description: "init"
    baseline-version: 0
  

    