CREATE TABLE IF NOT EXISTS post
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(5000)
);


-- ALTER TABLE post ADD created_at TIMESTAMP;
-- ALTER TABLE post ADD updated_at TIMESTAMP;


-- CREATE SEQUENCE post_seq
-- START WITH 1
-- INCREMENT BY 50
-- MINVALUE 0
-- MAXVALUE 999999999
-- CYCLE;